"""identidade externa e email: google_sub, email_confirmado, tokens_email

Revision ID: 56443b2f310a
Revises: 0becabba3bad
Create Date: 2026-09-13 02:24:59.187804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '56443b2f310a'
down_revision: Union[str, None] = '0becabba3bad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens_email',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Text(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['utilizadores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.add_column('utilizadores', sa.Column('google_sub', sa.Text(), nullable=True))
    op.add_column('utilizadores', sa.Column('email_confirmado', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('utilizadores', 'password_hash',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_unique_constraint('uq_utilizadores_google_sub', 'utilizadores', ['google_sub'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_utilizadores_google_sub', 'utilizadores', type_='unique')
    op.alter_column('utilizadores', 'password_hash',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('utilizadores', 'email_confirmado')
    op.drop_column('utilizadores', 'google_sub')
    op.drop_table('tokens_email')
    # ### end Alembic commands ###
